working

diff --git a/nsdf-fuse b/nsdf-fuse
--- a/nsdf-fuse
+++ b/nsdf-fuse
@@ -40,12 +40,15 @@ function Retry() {
 
 # /////////////////////////////////////////////////////////////////
 function CheckMount() {
-	__result__=$(mount | grep ${TEST_DIR})
+	__dir__=$1
+	echo "Checking mount..."
+	__result__=$(mount | grep ${__dir__})
 	if [ -z "$__result__" ] ; then
 		mount
-		echo "ERROR: ${TARGET} cannot mount ${TEST_DIR} "
+		echo "ERROR: cannot mount ${__dir__} "
 		exit 1
 	fi
+	echo "Check mount ok"
 }
 
 # /////////////////////////////////////////////////////////////////
@@ -62,8 +65,8 @@ function CleanAll() {
 		__mounted__=$(mount | grep ${BUCKETS_DIR} | cut -d" " -f3)
 		for it in $__mounted__; do 
 			echo "Unmounting $it"
-			sudo umount -l $it
-			sudo umount -f $it
+			sudo umount -l $it || true
+			sudo umount -f $it || true
 		done
 
 		# remove buckets
@@ -76,18 +79,18 @@ function CleanAll() {
 
 		# remove bucket dir
 		
-		sudo rm -Rf ${BUCKETS_DIR}/*
+		sudo rm -Rf /tmp/nsdf-fuse
 
 	done
 
-	echo "Mount"
+	echo "Mounted filesystem:"
 	$(mount | grep ${BUCKETS_DIR} | cut -d" " -f3)
 
-	echo "Buckets"
+	echo "Existing remote buckets:"
 	$(aws s3 ls | grep "nsdf-fuse-test" | cut -d" " -f3)
 
-	echo "${BUCKETS_DIR}"
-	find ${BUCKETS_DIR}/
+	echo "Content of ${BUCKETS_DIR}:"
+	find ${BUCKETS_DIR}/ 2>/dev/null || true
 }
 
 
@@ -125,32 +128,32 @@ function RunFioBenchmark() {
 	BeginTest fio-seq-1-write
 	fio  --name=fio-seq-1-write  --group_reporting=1 --directory=${TEST_DIR} --rw=write --bs=256k --size=${TOT_GB}G --refill_buffers 
 	EndTest fio-seq-1-write
-	nsdf-fuse ${TARGET} clean-bucket
+	nsdf-fuse clean-bucket
 
 	BeginTest fio-seq-1-read
 	fio  --name=fio-seq-1-read --group_reporting=1 --directory=${TEST_DIR} --rw=read --bs=256k --size=${TOT_GB}G --refill_buffers 
 	EndTest fio-seq-1-read
-	nsdf-fuse ${TARGET} clean-bucket
+	nsdf-fuse clean-bucket
 
 	BeginTest fio-seq-n-write	
 	fio  --name=fio-seq-n-write --group_reporting=1 --directory=${TEST_DIR} --rw=write --bs=256k  --size=${TOT_GB}G --refill_buffers  --numjobs=16  
 	EndTest fio-seq-n-write	
-	nsdf-fuse ${TARGET} clean-bucket
+	nsdf-fuse clean-bucket
 
 	BeginTest fio-seq-n-read
 	fio  --name=fio-seq-n-read --group_reporting=1 --directory=${TEST_DIR} --rw=read --bs=256k  --size=${TOT_GB}G --refill_buffers --numjobs=16 
 	EndTest fio-seq-n-read
-	nsdf-fuse ${TARGET} clean-bucket
+	nsdf-fuse clean-bucket
 
 	BeginTest fio-rand-1-write
 	fio  --name=fio-rand-1-write --group_reporting=1 --directory=${TEST_DIR} --rw=randwrite --bs=256k --size=${TOT_GB}G --refill_buffers 
 	EndTest fio-rand-1-write
-	nsdf-fuse ${TARGET} clean-bucket
+	nsdf-fuse clean-bucket
 
 	BeginTest fio-rand-1-read
 	fio  --name=fio-rand-1-read --group_reporting=1 --directory=${TEST_DIR} --rw=randread --bs=256k  --size=${TOT_GB}G 
 	EndTest fio-rand-1-read
-	nsdf-fuse ${TARGET} clean-bucket
+	nsdf-fuse clean-bucket
 }
 
 
@@ -158,7 +161,7 @@ function RunFioBenchmark() {
 function RunSimpleBenchmark() {
 
 	REMOTE=${TEST_DIR:?}
-	LOCAL=/tmp/simple-benchmark
+	LOCAL=/tmp/nsdf-fuse/local-storage
 
 	# ////////////////////////////////////////// 
 	# sequential
@@ -185,7 +188,7 @@ function RunSimpleBenchmark() {
 		done
 		EndTest simple-seq-1-read
 
-		nsdf-fuse ${TARGET} clean-bucket
+		nsdf-fuse clean-bucket
 
 		# simple-seq-n
 		BeginTest simple-seq-n-write
@@ -202,7 +205,7 @@ function RunSimpleBenchmark() {
 		done
 		EndTest simple-seq-n-read
 
-		nsdf-fuse ${TARGET} clean-bucket
+		nsdf-fuse clean-bucket
 	fi
 
 	# ///////////////////////////////////////////////
@@ -247,7 +250,7 @@ function RunSimpleBenchmark() {
 		done
 		EndTest simple-rand-n-read
 
-		nsdf-fuse ${TARGET} clean-bucket
+		nsdf-fuse clean-bucket
 	fi
 }
 
@@ -273,10 +276,82 @@ function InstallFIO() {
 }
 
 # //////////////////////////////////////////////////////////////////
+function CreateBucket()
+{
+	aws s3api create-bucket --bucket ${BUCKET_NAME:?} --region ${:?}
+}
+
+# //////////////////////////////////////////////////////////////////
+function RemoveBucket() {
+	# note: there is a prefix
+	aws s3 rb s3://${BUCKET_NAME:?} --force
+}
+
+# //////////////////////////////////////////////////////////////////
+function ConfigTarget() {
+
+	# target specific
+	# please specify a target as an environment variable
+	__target__=${TARGET:?}
+
+	export BUCKET_NAME=nsdf-fuse-test-${__target__}
+	export BASE_DIR=${BUCKETS_DIR}/${BUCKET_NAME}
+	export TEST_DIR=${BASE_DIR}/test
+	export CACHE_DIR=${BASE_DIR}/cache
+	export LOG_DIR=${BASE_DIR}/log
+
+	echo "NSDF-fuse v1.0"
+	echo "   BUCKET_NAME=${BUCKET_NAME}"
+	echo "   AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}"
+	echo "   BASE_DIR=${BASE_DIR}"
+	echo "   TEST_DIR=${TEST_DIR}"
+	echo "   CACHE_DIR=${CACHE_DIR}"
+	echo "   LOG_DIR=${LOG_DIR}"
+
+		 # make sure I have all the directories
+	mkdir  -p ${BASE_DIR}  || true
+	mkdir  -p ${TEST_DIR}  || true
+	mkdir  -p ${CACHE_DIR} || true
+	mkdir  -p ${LOG_DIR}   || true
+
+	# add some functions (as CreateBucket, RemoveBucket, FuseUp and FuseDown)
+	if   [[  "${__target__}" == "geesefs" ]] ; then 
+		source scripts/geesefs.sh 
+
+	elif [[  "${__target__}" == "goofys"  ]] ; then 
+		source scripts/goofys.sh 
+
+	elif [[  "${__target__}" == "juicefs" ]] ; then 
+		source scripts/juicefs.sh 
+
+	elif [[  "${__target__}" == "objectivefs" ]] ; then 
+		source scripts/objectivefs.sh
+
+
+	elif [[  "${__target__}" == "rclone" ]] ; then 
+		source scripts/rclone.sh	
+
+	elif [[  "${__target__}" == "s3backer" ]] ; then 
+		source scripts/s3backer.sh
+
+	elif [[  "${__target__}" == "s3fs" ]] ; then 
+		source scripts/s3fs.sh
+		  
+	elif [[  "${__target__}" == "s3ql" ]] ; then 
+		source scripts/s3ql.sh
+
+	else
+		echo "ERROR: unknown TARGET=${__target__}"
+		exit 1
+	fi
+}
+
+
+# //////////////////////////////////////////////////////////////////
 function Main() {
 
 	# all test are meant to be temporary
-	export BUCKETS_DIR=/tmp/buckets
+	export BUCKETS_DIR=/tmp/nsdf-fuse/buckets
 	mkdir -p $BUCKETS_DIR
 
 	if [[ "$1" == "clean-all" ]] ; then
@@ -292,58 +367,10 @@ function Main() {
 		exit 0
 	fi
 
-	# target specific
-	TARGET=${1:?}
-	shift
+	# need a target from here
+	ConfigTarget
 
-	export BUCKET_NAME=nsdf-fuse-test-${TARGET}
-	export BASE_DIR=${BUCKETS_DIR}/${BUCKET_NAME}
-	export TEST_DIR=${BASE_DIR}/test
-	export CACHE_DIR=${BASE_DIR}/cache
-	export LOG_DIR=${BASE_DIR}/log
-
-	echo "# BUCKET_NAME=${BUCKET_NAME} AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION} BASE_DIR=${BASE_DIR} TEST_DIR=${TEST_DIR} CACHE_DIR=${CACHE_DIR} LOG_DIR=${LOG_DIR}"
-
-		 # make sure I have all the directories
-	mkdir  -p ${BASE_DIR}  || true
-	mkdir  -p ${TEST_DIR}  || true
-	mkdir  -p ${CACHE_DIR} || true
-	mkdir  -p ${LOG_DIR}   || true
-
-
-	# add some functions (as CreateBucket, RemoveBucket, FuseUp and FuseDown)
-	if   [[  "${TARGET}" == "geesefs" ]] ; then 
-		source scripts/geesefs.sh 
-
-	elif [[  "${TARGET}" == "goofys"  ]] ; then 
-		source scripts/goofys.sh 
-
-	elif [[  "${TARGET}" == "juicefs" ]] ; then 
-		source scripts/juicefs.sh 
-
-	elif [[  "${TARGET}" == "objectivefs" ]] ; then 
-		source scripts/objectivefs.sh
-
-	elif [[  "${TARGET}" == "rclone" ]] ; then 
-		source scripts/rclone.sh	 
-
-	elif [[  "${TARGET}" == "s3backer" ]] ; then 
-		source scripts/s3backer.sh
-
-	elif [[  "${TARGET}" == "s3fs" ]] ; then 
-		source scripts/s3fs.sh
-		  
-	elif [[  "${TARGET}" == "s3ql" ]] ; then 
-		source scripts/s3ql.sh
-		  
-	else
-		echo "ERROR: unknown TARGET=${TARGET}"
-	fi
-
-	# //////////////////////////////////////////////////////////////
 	while (( "$#" )) ; do
-
-		set -e
 
 		ACTION=${1:?}
 		shift
@@ -383,7 +410,7 @@ function Main() {
 			FuseDown 
 
 		elif [[ "${ACTION}" == "touch" ]] ; then
-			echo "it is working" > $TEST_DIR/it_is_working
+			echo "nsdf_test_body" > ${TEST_DIR}/nsdf_test_file
 
 		# "WARNING: remember to create-bucket
 		elif [[ "${ACTION}" == "fio-benchmark" ]] ; then
@@ -405,9 +432,11 @@ function Main() {
 	done
 }
 
+# //////////////////////////////////////////////////////////////////
 if [[ $# -ge 1 ]]; then
 	Main $@
 fi
+
 
 
 
